
import type {NextPage} from 'next'
import Head from 'next/head'
import {useForm, SubmitHandler, Controller} from "react-hook-form";
import styles from '../styles/Home.module.css'
import SelectInput from "../components/SelectInput";
import {Button} from "@chakra-ui/react";


type Inputs = {
  nameList: string[],
};

const Home: NextPage = () => {
  const {register, handleSubmit, control, watch, formState: {errors}, setValue} = useForm<Inputs>();
  const onSubmit: SubmitHandler<Inputs> = data => {
    console.log("data", data)
    console.log("register", register)
  }
  console.log(watch("nameList"))
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <form onSubmit={handleSubmit(data => console.log(data))}>
          <Controller
            control={control}
            name='nameList'
            render={({field}) => (
              <SelectInput
                {...field}
                setValue={setValue}
                title="賃貸用途"
                initData={["事務所", "店舗"]}
              />
            )}
          />
          <Button type="submit">save</Button>
        </form>
      </main>
    </div>
  )
}

export default Home
